config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  devise_for :users

  resources :games do
    resources :ratings do
    end
  end

  post 'reviews/:id/upvote', to: 'votes#upvote', as: :upvote_rating
  post 'reviews/:id/downvote', to: 'votes#downvote', as: :downvote_rating

  get 'user/:id', to: 'users#show', as: :show_user
  post 'user/:id/ban', to: 'users#ban', as: :ban_user

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :ratings
  has_many :games, through: :ratings
  has_many :added_games, class_name: 'Game'

  validates :username, presence: true, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @reviews = @user.ratings.paginate(page: params[:page])
  end

  def ban
    if current_user.admin?
      @user = User.find_by(id: params[:id])
      @user.banned = true
      @user.ratings.delete_all
      @user.save
    end

    redirect_to root_path
  end

end

app/views/users/_user_reviews.html.erb
<div class="row game <%= 'even' if review_counter % 2 == 0 %>">
  <div class="col-xs-2 game-name">
    <%= link_to review.game.title, show_game_path(steam_appid: review.game.steam_appid) %>
    <%= link_to image_tag(review.game.header_image, class: 'game-image'), show_game_path(steam_appid: review.game.steam_appid)  %>
    <%= link_to 'View full review', show_rating_path(steam_appid: review.game.steam_appid, id: review.id) %>
  </div>
  <div class="col-xs-1 ranking stat">
    <%= image_tag review.ranking.to_s + '.jpg' %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :framerate %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :resolution %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :optimization %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :mods %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :servers %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :dlc %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :bugs %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :settings %>
  </div>
  <div class="col-xs-1 stat">
    <%= review.get_rounded_stat :controls %>
  </div>
</div>

app/views/users/_user_reviews_mobile.html.erb
<div class="row game <% 'even' if review_counter % 2 == 0 %>">
  <div class="col-xs-6 game-name">
    <%= link_to review.game.title, show_game_path(steam_appid: review.game.steam_appid) %>
    <%= link_to image_tag(review.game.header_image, class: 'game-image'), show_game_path(steam_appid: review.game.steam_appid)  %>
  </div>
  <div class="col-xs-6 ranking stat">
    <%= image_tag review.game.ranking.to_s + '.jpg', class: 'mobile' %>
  </div>
</div>

app/views/users/show.html.erb
<h3>
  <%= @user.username %>'s profile
</h3>

<% if current_user && current_user.admin? %>
  <%= link_to 'Ban user', ban_user_path(id: @user.id), method: :post %>
<% end %>

<% if @user.banned? %>
  BANNED
<% end %>

<h3>
  <%= @user.username %>'s reviews
</h3>

<div class="game-index">
  <div class="hidden-xs">
    <div class="row headers">
      <div class="col-xs-2">
        Name
      </div>
      <div class="col-xs-1">
        Ranking
      </div>
      <div class="col-xs-1">
        Framerate
      </div>
      <div class="col-xs-1">
        Resolution
      </div>
      <div class="col-xs-1">
        Optimization
      </div>
      <div class="col-xs-1">
        Mods
      </div>
      <div class="col-xs-1">
        Servers
      </div>
      <div class="col-xs-1">
        DLC
      </div>
      <div class="col-xs-1">
        Bugs
      </div>
      <div class="col-xs-1">
        Settings
      </div>
      <div class="col-xs-1">
        Controls
      </div>
    </div>

    <%= render partial: 'user_reviews', collection: @reviews, as: :review %>
  </div>

  <div class="visible-xs">
    <div class="row headers">
      <div class="col-xs-6">
        Name
      </div>
      <div class="col-xs-6">
        Ranking
      </div>
    </div>

    <%= render partial: 'user_reviews_mobile', collection: @reviews, as: :review %>
  </div>

  <%= will_paginate @reviews %>

</div>

<script>
  var sticky = new Waypoint.Sticky({
    element: $('.game-index .headers')[0]
  })
</script>