config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  devise_for :users

  resources :games do
    resources :ratings do
    end
  end

  post 'reviews/:id/upvote', to: 'votes#upvote', as: :upvote_rating
  post 'reviews/:id/downvote', to: 'votes#downvote', as: :downvote_rating

  get 'user/:id', to: 'users#show', as: :show_user
  post 'user/:id/ban', to: 'users#ban', as: :ban_user

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  acts_as_votable

  belongs_to :user
  belongs_to :game

  validates_uniqueness_of :user_id, scope: :game_id

  validates :user, :game, :framerate, :resolution, :optimization, presence: true
  validates :dlc, :bugs, :settings, :controls, :servers, :mods, presence: true

  # TODO: Pull out of this class
  CATEGORY_WEIGHTS = {
    framerate: 8, resolution: 7, optimization: 9, mods: 3,
    servers: 5, dlc: 4, bugs: 6, settings: 2, controls: 1
  }

  # TODO: Move these enums elsewhere, they're clogging up the class.
  enum framerate: {
    :'May be capped to 30 FPS' => 0,
    :'May be capped to 60 FPS' => 1,
    :'60 FPS capped' => 2,
    :'60 FPS capped, potentially limitless' => 3,
    :'Limitless (like your dreams)' => 4
  }

  enum resolution: {
    :'Does not support 1080p' => 0,
    :'Limited 1080p support' => 1,
    :'Supports 1080p' => 2,
    :'Supports 1080p with multi-monitor support' => 3,
    :'4k and beyond' => 4
  }

  enum optimization: {
    Poor: 0,
    Passable: 1,
    Good: 2,
    Great: 3,
    Glorious: 4
  }

  enum mods: {
    :'No support/May result in online bans' => 0,
    :'Unofficial support/Heavily restricted' => 1,
    :'Unofficial support, may be limited to cosmetic changes' => 2,
    :'Official support, modding tools are limited' => 3,
    :'Complete support, modding tools close to tools developers used' => 4
  }

  enum servers: {
    :'Unstable servers. Likely to shut down early.' => 0,
    :'Partially stable servers.' => 1,
    :'Servers unstable at high volume.' => 2,
    :'Acceptable servers' => 3,
    :'Reliable servers or dedicated server software available (or Single Player)' => 4
  }

  enum dlc: {
    :'Day 1 DLC, affects game balance' => 0,
    :'Day 1 DLC, cosmetic only' => 1,
    :'No Day 1 DLC' => 2,
    :'Day 1 DLC is free and provides useful content' => 3,
    :'Large content patches in the style of old expansions or no DLC' => 4
  }

  enum bugs: {
    :'Constant game breaking bugs. Unplayable' => 0,
    :'Excessively buggy, mostly playable' => 1,
    :'Playable but often encounter bugs' => 2,
    :'A few bugs here and there, but rarely do they affect enjoyment' => 3,
    :'Rare bugs. Possible to go entire game without encountering' => 4
  }

  enum settings: {
    :'No settings to change' => 0,
    :'Limited settings, no video options' => 1,
    :'Preset video settings only (Low, Medium, High)' => 2,
    :'Acceptable video settings, can change most things' => 3,
    :'Complete video settings, can change and turn off everything' => 4
  }

  enum controls: {
    :'Cannot configure controls. Controls still displayed as console buttons in in interface' => 0,
    :'Cannot configure controls. Gamepad support' => 1,
    :'Sensitivity options, can remap some keys' => 2,
    :'Can remap most keys, gamepad support, sensitivity controls' => 3,
    :'Can use a range of devices, remap all keys, have alternate control sets, and set sensitivity' => 4
  }

  def self.ranking(score)
    case score
    when 0..35
      :p
    when 36..71
      :c
    when 71..107
      :m
    when 108..143
      :r
    when 143..180
      :g
    else
      :no_ratings
    end
  end

  def self.visible
    all.select do |rating|
      !rating.hidden?
    end
  end

  def hidden?
    score < -3
  end

  def score
    cached_votes_score
  end

  def get_stat(stat)
    self[stat]
  end

  def get_rounded_stat(stat)
    get_stat(stat).round
  end

  def ranking
    Rating.ranking(total)
  end

  def total
    total = 0
    CATEGORY_WEIGHTS.each do |category, weight|
      total += self[category] * weight
    end

    total
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :user?, except: [:show]
  before_action :admin?, only: [:destroy]

  def show
    @game = Game.find_by(slug: params[:game_id])
    @rating = Rating.find_by(id: params[:id], game: @game)
  end

  def edit
    @game = Game.find_by(slug: params[:game_id])
    @rating = Rating.find_by(user: current_user, game: @game)

    redirect_to game_path(id: @game.slug) unless @rating
  end

  def new
    @game = Game.find_by(slug: params[:game_id])
    @rating = @game.ratings.new
  end

  def create
    @game = Game.find_by(slug: params[:game_id])
    @rating = Rating.new(permitted_params)
    @rating.user = current_user
    @rating.game = @game

    if @rating.save
      redirect_to game_path(id: @game.slug)
    else
      render :new
    end
  end

  def update
    @game = Game.find_by(slug: params[:game_id])
    @rating = Rating.find_by(user: current_user, game: @game)
    @rating.update_attributes(permitted_params)

    redirect_to game_rating_path(game_id: @rating.game, id: @rating.id)
  end

  def destroy
    @game = Game.find_by(slug: params[:game_id])
    @rating = Rating.find_by(id: params[:id])

    @rating.destroy if @rating

    redirect_to game_path(id: @game.slug)
  end

  private

  def user?
    flash[:success] = 'Login or signup to continue'
    redirect_to new_user_session_path unless current_user
  end

  def admin?
    redirect_to root_path unless current_user.admin?
  end

  def owned_by_user?
    redirect_to root_path unless @rating.user == current_user
  end

  def permitted_params
    params.require(:rating).permit(
      :framerate, :resolution, :optimization, :mods,
      :servers, :dlc, :bugs, :settings, :controls, :review)
  end

end

app/views/ratings/edit.html.erb
<div class="rating-form">
  <div class="row">
    <div class="col-xs-12">
      <%= @rating.errors.messages if @rating && @rating.errors.size > 0 %>

      <div class="row images">
        <div class="col-xs-6">
          <h3>
            Editing your review for <%= @game.title %>
          </h3>
        </div>
        <div class="col-xs-6 col-sm-2">
          <%= image_tag(@game.header_image) %>
        </div>
      </div>

      <%= form_for @rating, url: game_rating_path(id: @rating.id) do |f| %>
        <div class="row">
          <div class="col-xs-6">
            <div>
              <%= f.label "Frame rate:" %>
              <%= f.select :framerate, options_for_select(Rating.framerates.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Resolution:" %>
              <%= f.select :resolution, options_for_select(Rating.resolutions.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Optimization:" %>
              <%= f.select :optimization, options_for_select(Rating.optimizations.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Mods:" %>
              <%= f.select :mods, options_for_select(Rating.mods.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Servers:" %>
              <%= f.select :servers, options_for_select(Rating.servers.keys), {}, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6">
            <div>
              <label>DLC:</label>
              <%= f.select :dlc, options_for_select(Rating.dlcs.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Buggyness:" %>
              <%= f.select :bugs, options_for_select(Rating.bugs.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Settings:" %>
              <%= f.select :settings, options_for_select(Rating.settings.keys, {}), class: "form-control" %>
            </div>

            <div>
              <%= f.label "Controls:" %>
              <%= f.select :controls, options_for_select(Rating.controls.keys), {}, class: "form-control" %>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <%= f.label "Review:" %>
            <%= f.text_area :review, placeholder: :Review, value: @rating.review, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6 col-xs-offset-3">
            <%= f.button "Update Review", class: "btn btn-success" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/ratings/new.html.erb
<div class="rating-form">
  <div class="row">
    <div class="col-xs-12">
      <%= @rating.errors.messages if @rating && @rating.errors.size > 0 %>

      <div class="row images">
        <div class="col-xs-6">
          <h3>
            New review for <%= @game.title %>
          </h3>
        </div>
        <div class="col-xs-6 col-sm-2">
          <%= image_tag(@game.header_image) %>
        </div>
      </div>

      <%= form_for @rating, url: game_ratings_path do |f| %>
        <div class="row">
          <div class="col-xs-6">
            <div>
              <%= f.label "Frame rate:" %>
              <%= f.select :framerate, options_for_select(Rating.framerates.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Resolution:" %>
              <%= f.select :resolution, options_for_select(Rating.resolutions.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Optimization:" %>
              <%= f.select :optimization, options_for_select(Rating.optimizations.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Mods:" %>
              <%= f.select :mods, options_for_select(Rating.mods.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Servers:" %>
              <%= f.select :servers, options_for_select(Rating.servers.keys), {}, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6">
            <div>
              <label>DLC:</label>
              <%= f.select :dlc, options_for_select(Rating.dlcs.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Buggyness:" %>
              <%= f.select :bugs, options_for_select(Rating.bugs.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Settings:" %>
              <%= f.select :settings, options_for_select(Rating.settings.keys), {}, class: "form-control" %>
            </div>

            <div>
              <%= f.label "Controls:" %>
              <%= f.select :controls, options_for_select(Rating.controls.keys), {}, class: "form-control" %>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <%= f.label "Review:" %>
            <%= f.text_area :review, placeholder: :Review, value: @rating.review, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6 col-xs-offset-3">
            <%= f.button "Submit Review", class: "btn btn-success" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/ratings/show.html.erb
<div class="rating-show">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">

      <h3>
        <%= @rating.game.title %> review <%= "by #{@rating.user.username}" if @rating.user.username %>
      </h3>

      <%= link_to "Back to game page", game_path(id: @rating.game.slug), class: 'back-link' %>

      <div class="row images">
        <div class="col-xs-8">
          <%= image_tag(@game.header_image) %>
        </div>
        <div class="col-xs-4 ranking">
          <%= image_tag(@game.ranking.to_s + '.jpg') if @game.ratings.size > 0 %>
        </div>
      </div>

      <div>
        <%= label_tag '', "Framerate: " %><%= @rating.framerate %>
      </div>

      <div>
        <%= label_tag '', "Resolution: " %><%= @rating.resolution %>
      </div>

      <div>
        <%= label_tag '', "Optimization: " %><%= @rating.optimization %>
      </div>

      <div>
        <%= label_tag '', "Mods: " %><%= @rating.mods %>
      </div>

      <div>
        <%= label_tag '', "Servers: " %><%= @rating.servers %>
      </div>

      <div>
        <%= label_tag '', "DLC: " %><%= @rating.dlc %>
      </div>

      <div>
        <%= label_tag '', "Bugs: " %><%= @rating.bugs %>
      </div>

      <div>
        <%= label_tag '', "Settings: " %><%= @rating.settings %>
      </div>

      <div>
        <%= label_tag '', "Controls: " %><%= @rating.controls %>
      </div>

      <% unless @rating.review.blank? %>
        <div>
          <%= label_tag '', "Review: " %><%= @rating.review %>
        </div>
      <% end %>

      <div>
        <%= link_to("▲", upvote_rating_path(id: @rating.id)) %>
        <%= link_to("▼", downvote_rating_path(id: @rating.id)) %>
        <%= @rating.score %>
      </div>

    </div>
  </div>
</div>