config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  devise_for :users

  resources :games do
    resources :ratings do
    end
  end

  post 'reviews/:id/upvote', to: 'votes#upvote', as: :upvote_rating
  post 'reviews/:id/downvote', to: 'votes#downvote', as: :downvote_rating

  get 'user/:id', to: 'users#show', as: :show_user
  post 'user/:id/ban', to: 'users#ban', as: :ban_user

end

app/models/game.rb
class Game < ActiveRecord::Base
  extend FriendlyId

  require 'net/http'

  serialize :data

  has_many :ratings
  has_many :users, through: :ratings

  belongs_to :user

  validates :steam_appid, uniqueness: true

  before_create :request_game_data
  friendly_id :title, use: :slugged

  def rating
    ratings_array = ratings.visible

    return false if ratings_array.size == 0

    total = 0

    ratings_array.each do |rating|
      total += rating.total
    end

    total / ratings_array.size
  end

  # Stats

  def ranking
    Rating.ranking(rating)
  end

  def get_stat_string(stat)
    value = get_stat stat

    return 'N/A' if value.nan?

    Rating.send(stat.to_s.pluralize.to_sym).to_a[value][0]
  end

  def get_stat(stat)
    average_array ratings.visible.map { |rating| rating[stat] }
  end

  def get_rounded_stat(stat)
    get_stat(stat).round
  end

  def average_array(array)
    array.inject { |a, e| a + e }.to_f / array.size
  end

  # Static Data

  def description
    desc = data[data.keys[0]]['data']['detailed_description'] if data
    return desc.html_safe if desc
  end

  def dlc
    data[data.keys[0]]['data']['dlc'] if data
  end

  def min_requirements
    req = data[data.keys[0]]['data']['pc_requirements']['minimum'] if data
    return req.html_safe if req
  end

  def recommended_requirements
    req = data[data.keys[0]]['data']['pc_requirements']['recommended'] if data
    return req.html_safe if req
  end

  def developers
    data[data.keys[0]]['data']['developers'] if data
  end

  def publishers
    data[data.keys[0]]['data']['publishers'] if data
  end

  def header_image
    data[data.keys[0]]['data']['header_image'] if data
  end

  def website
    data[data.keys[0]]['data']['website'] if data
  end

  def launch_game_link
    "steam://run/#{self.steam_appid}"
  end

  def rated_by_user?(user)
    return false unless user

    rating = Rating.find_by(user_id: user.id, game_id: id)

    return true if rating
  end

  private

  def request_game_data
    url = "http://store.steampowered.com/api/appdetails/?appids=#{steam_appid}"
    resp = Net::HTTP.get_response(URI.parse(url))
    data = JSON.parse(resp.body)

    if data[data.keys[0]]['data'].blank? || resp.code == '403'
      errors.add :Game, 'does not exist'
      return false
    end

    copy_data data
  end

  # Copy data out of the data parcel returned
  # by the Steam API into the Game model's fields
  def copy_data(data)
    self.data = data
    self.title = data[data.keys[0]]['data']['name']
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :user?, except: [:index, :show]
  before_action :admin?, only: [:destroy]
  before_action :setup_game, except: [:index, :new, :create]

  def index
    @q = Game.ransack(params[:q])
    @games = @q.result.paginate(page: params[:page], per_page: 6)
  end

  def show
    if @game
      @reviews = @game.ratings.paginate(page: params[:page], per_page: 6)
    else
      @game = Game.new(steam_appid: params[:steam_appid])
      render :new
    end
  end

  def edit
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(permitted_params.merge(user: current_user))
    @game.save
    @game.save
    flash[:error] = @game.errors.full_messages[0]
    redirect_to game_path(id: @game.slug)
  end

  def destroy
    @game.destroy
  end

  private

  def user?
    flash[:success] = 'Login or signup to continue'
    redirect_to new_user_session_path unless current_user
  end

  def admin?
    redirect_to root_path unless current_user.admin?
  end

  def setup_game
    @game = Game.friendly.find(params[:id])
  end

  def permitted_params
    params.require(:game).permit(:steam_appid)
  end

end

app/views/games/_game_index_row.html.erb
<div class="row game <%= 'even' if game_counter % 2 == 0 %>">
  <div class="col-xs-2 game-name">
    <%= link_to game.title, game_path(id: game.slug) %>
    <%= link_to image_tag(game.header_image, class: 'game-image'), game_path(id: game.slug) %>
    <%= link_to "See Reviews", game_path(id: game.slug), class: 'btn btn-success' %>
    <%= link_to "Add a Review", new_game_rating_path(game_id: game.slug), class: 'btn btn-success' %>
  </div>

  <% if game.ratings.size > 0 %>
    <div class="col-xs-1 ranking stat">
      <%= image_tag(game.ranking.to_s + '.jpg') %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :framerate %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :resolution %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :optimization %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :mods %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :servers %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :dlc %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :bugs %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :settings %>
    </div>
    <div class="col-xs-1 stat">
      <%= game.get_rounded_stat :controls %>
    </div>
  <% end %>
</div>

app/views/games/_game_index_row_mobile.html.erb
<div class="row game <% 'even' if game_counter % 2 == 0 %>">
  <div class="col-xs-6 game-name">
    <%= link_to game.title, game_path(id: game.slug) %>
    <%= link_to image_tag(game.header_image, class: 'game-image'), game_path(id: game.slug)  %>
  </div>
  <div class="col-xs-6 ranking stat">
    <%= image_tag game.ranking.to_s + '.jpg', class: 'mobile' %>
  </div>
</div>

app/views/games/_game_show_stats.html.erb
<% if @game.ratings.size > 0 %>
  <div class="rating row bottom-separator">
    <div class="col-xs-12">
      <h3>Average Rating</h3>
      <ul>
        <li>
          <label>Framerate:</label> <%= @game.get_stat_string :framerate %>
        </li>
        <li>
          <label>Resolution:</label> <%= @game.get_stat_string :resolution %>
        </li>
        <li>
          <label>Optimization:</label> <%= @game.get_stat_string :optimization %>
        </li>
        <li>
          <label>Mods:</label> <%= @game.get_stat_string :mods %>
        </li>
        <li>
          <label>Servers:</label> <%= @game.get_stat_string :servers %>
        </li>
        <li>
          <label>DLC:</label> <%= @game.get_stat_string :dlc %>
        </li>
        <li>
          <label>Bugs:</label> <%= @game.get_stat_string :bugs %>
        </li>
        <li>
          <label>Settings:</label> <%= @game.get_stat_string :settings %>
        </li>
        <li>
          <label>Controls:</label> <%= @game.get_stat_string :controls %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/games/_review.html.erb
<div class="review">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to review.user.username, show_user_path(id: review.user.id) %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6"><label>Framerate:</label> <%= review.framerate %></div>
    <div class="col-xs-12 col-sm-6"><label>Resolution:</label> <%= review.resolution %></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6"><label>Optimization:</label> <%= review.optimization %></div>
    <div class="col-xs-12 col-sm-6"><label>Mods:</label> <%= review.mods %></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6"><label>Servers:</label> <%= review.servers %></div>
    <div class="col-xs-12 col-sm-6"><label>DLC:</label> <%= review.dlc %></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6"><label>Bugs:</label> <%= review.bugs %></div>
    <div class="col-xs-12 col-sm-6"><label>Settings:</label> <%= review.settings %></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6"><label>Controls:</label> <%= review.controls %></div>
  </div>

  <% unless review.review.blank? %>
    <div class="row">
      <div class="col-xs-12 review-text">
        <label>Review</label>
        <%= review.review %>
      </div>
    </div>
  <% end %>

  <% if current_user && current_user.admin? %>
    <%= link_to 'Delete', game_rating_path(game_id: review.game.slug, id: review.id), method: :delete %>
  <% end %>

  <div>
    <%= link_to("▲", upvote_rating_path(id: review.id), method: :post) %>
    <%= link_to("▼", downvote_rating_path(id: review.id), method: :post) %>
    <%= review.score %>
  </div>

</div>

app/views/games/index.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <%= link_to 'Add a game', new_game_path, class: 'btn btn-info full-width' %>
  </div>
</div>

<div class="row search-form">
  <%= search_form_for @q do |f| %>
    <div class="col-xs-4 col-xs-offset-3">
      <%= f.search_field :title_cont, placeholder: 'Search by Title', class: 'form-control' %>
      If the game you're looking for doesn't exist, add it!
    </div>
    <div class="col-xs-2">
      <%= f.submit "Search", class: 'btn btn-success full-width' %>
    </div>
  <% end %>
</div>

<div class="game-index">
  <div class="hidden-xs">
    <div class="row headers">
      <div class="col-xs-2">
        Name
      </div>
      <div class="col-xs-1">
        Ranking
      </div>
      <div class="col-xs-1">
        Framerate
      </div>
      <div class="col-xs-1">
        Resolution
      </div>
      <div class="col-xs-1">
        Optimization
      </div>
      <div class="col-xs-1">
        Mods
      </div>
      <div class="col-xs-1">
        Servers
      </div>
      <div class="col-xs-1">
        DLC
      </div>
      <div class="col-xs-1">
        Bugs
      </div>
      <div class="col-xs-1">
        Settings
      </div>
      <div class="col-xs-1">
        Controls
      </div>
    </div>

    <%= render partial: 'game_index_row', collection: @games, as: :game %>
  </div>

  <div class="visible-xs">
    <div class="row headers">
      <div class="col-xs-6">
        Name
      </div>
      <div class="col-xs-6">
        Ranking
      </div>
    </div>

    <%= render partial: 'game_index_row_mobile', collection: @games, as: :game %>
  </div>

  <%= will_paginate @reviews %>

</div>

app/views/games/new.html.erb
<%= @game.errors.messages if @game && @game.errors.size > 0 %>

<div class="row new-game-form">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= form_for @game do |f| %>
      <%= f.text_field :steam_appid, value: @game.steam_appid, class: "form-control", placeholder: "Steam App ID (instructions below)" %>
      <%= f.button "Add Game", class: "btn btn-success" %>
    <% end %>

    <div class="row add-game-instructions">
      <div class="col-xs-12">
        <h3>Getting the Steam App ID</h3>
        <ol>
          <li>
            <b>Search for the game on SteamDB:</b><br>
            <form action="https://steamdb.info/search/" target="_blank">
              <input type="hidden" name="a" value="app">
              <input name="q" placeholder="Electronic Super Joy" class="form-control">
              <button type="submit" class="btn btn-info full-width">Search SteamDB</button>
            </form>
          </li>
          <li>
            <b>Input the game's AppID above:</b><br>
            <%= image_tag "https://i.imgur.com/aujtOhq.png" %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<% meta title: "#{@game.title} Reviews for PC" ,
        description: "#{@game.title} reviews for PC platform.",
        keywords: %w(@game.title pcmr pcmasterrace pcrating pcglorious),
        og: {
          title: "#{@game.title} Reviews for PC" ,
          site_name: "PCMRating",
          url: game_url(@game.slug),
          image: @game.header_image
        } %>

<div class="game-show-page">
  <div class="game-title">
    <h1><%= @game.title %></h1>
    <label>Total Reviews:</label> <%= @game.ratings.size %>
  </div>

  <div class="row">

    <div class="col-xs-8 left">

      <div class="row bottom-separator images">
        <div class="col-xs-8">
          <%= image_tag(@game.header_image) %>
        </div>
        <div class="col-xs-4 ranking">
          <%= image_tag(@game.ranking.to_s + '.jpg') if @game.ratings.size > 0 %>
        </div>
      </div>

      <div class="row bottom-separator">
        <div class="col-xs-12">
          <div>
            <%= link_to('Write Review', new_game_rating_path(@game.slug), class: 'btn btn-success full-width') unless @game.rated_by_user? current_user %>
            <%= link_to('Edit Your Review', edit_game_rating_path(@game.slug, Rating.where(game_id: @game.id).where(user_id: current_user.id).first.id), class: 'btn btn-success full-width') if @game.rated_by_user? current_user %>
          </div>
        </div>
      </div>

      <div class="row bottom-separator steam-description">
        <div class="col-xs-12">
          <div class="show-description" onClick="$('.description').toggle(500); $('.show-description .view, .show-description .unview').toggle(); ">
            <span class="view">View</span><span class="unview">Hide</span> Steam Description
          </div>
          <div class="description">
            <%= @game.description %>
          </div>
        </div>
      </div>

      <%= render 'game_show_stats' %>

      <div class="row reviews">
        <div class="col-xs-12">
          <h3>Reviews</h3>
          <div>
            <%= link_to('Write Review', new_game_rating_path(@game.slug), class: 'btn btn-success full-width') unless @game.rated_by_user? current_user %>
            <%= link_to('Edit Your Review', edit_game_rating_path(@game.slug, Rating.where(game_id: @game.id).where(user_id: current_user.id).first.id), class: 'btn btn-success full-width') if @game.rated_by_user? current_user %>
          </div>

          <%= render partial: 'review', collection: @reviews %>

          <%= will_paginate @reviews %>
        </div>
      </div>

    </div>

    <div class="col-xs-4 right">
      <div class="row bottom-separator">
        <div class="col-xs-12">
          <h3>Game Information</h3>
          <% if @game.dlc %>
            <div>
              <label>Total DLC:</label> <%= @game.dlc.size %>
            </div>
          <% end %>
          <div>
            <label>Developers:</label> <%= @game.developers[0] %>
          </div>
          <div>
            <label>Publishers:</label> <%= @game.publishers[0] %>
          </div>
          <div>
            <label>Website:</label> <%= link_to @game.website %>
          </div>
          <div>
            <label><%= link_to "View on Steam", "http://store.steampowered.com/app/#{@game.steam_appid}/" %>
          </div>
          <div>
            <%= link_to 'Launch this game using steam', @game.launch_game_link, class: 'btn btn-success full-width' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <h3>Requirements</h3>
          <div>
            <%= @game.min_requirements %>
          </div>
          <div>
            <%= @game.recommended_requirements %>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>