config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  devise_for :users

  resources :games do
    resources :ratings do
    end
  end

  post 'reviews/:id/upvote', to: 'votes#upvote', as: :upvote_rating
  post 'reviews/:id/downvote', to: 'votes#downvote', as: :downvote_rating

  get 'user/:id', to: 'users#show', as: :show_user
  post 'user/:id/ban', to: 'users#ban', as: :ban_user

end

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <%= link_to 'Help improve the site on Github', 'https://github.com/PCMRating/pcmrating', target: '_blank' %>
      </div>
      <div class="col-xs-6 right">
        <%= link_to '/r/pcmasterrace', 'http://www.reddit.com/r/pcmasterrace', target: '_blank' %>
      </div>
    </div>
  </div>
</footer>

app/views/common/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PCMRatings', root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Hello #{current_user.username}", show_user_path(current_user.id) %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Post Feedback', ENV['REDDIT_LINK']) if ENV['REDDIT_LINK'] %></li>
        <li><%= link_to("Add a new game", new_game_path) if current_user %></li>
        <li><%= link_to "View Games", games_path %></li>
        <% if current_user %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>